version: 1.0.{build}

image: Visual Studio 2017

configuration:
- Release

platform: Any CPU

before_build:
- nuget restore -verbosity quiet

build:
 project: SourceCode.SmartObjects.Services.Tests.sln
 verbosity: minimal

test_script:
- vstest.console /Platform:x64 /InIsolation /logger:Appveyor "src\Tests\UTest\bin\Release\SourceCode.SmartObjects.Services.Tests.UTest.dll"

deploy:
  provider: NuGet
  api_key:
    secure: 9ZjxrStO3j210yUXmH4Q5/H7Bkepb+A1f3kn0snparetNCiXA7sYHvQLRVlAt94m
  on:
    branch: master
is_not_pr: true