version: '1.0.{build}'
configuration:
- Release
platform: Any CPU
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "preview1-" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
- ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { $env:is_not_pr = "true"; }
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\SourceCode.SmartObjects.Services.Tests.csproj" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
