version: 1.0.{build}

image: Visual Studio 2017

configuration:
- Release

platform: Any CPU

before_build:
- nuget restore

build:
 project: SourceCode.SmartObjects.Services.Tests.sln
 verbosity: minimal

before_test:
- cd build
- powershell -Command .\build.ps1
- cd ..

test_script:
- vstest.console /logger:Appveyor "C:\projects\SourceCode.SmartObjects.Services.Tests.UTest.dll"