version: 1.0.{build}

image: Visual Studio 2017

configuration:
- Release

platform: Any CPU

before_build:
- nuget restore

build:
 project: SourceCode.SmartObjects.Services.Tests.sln
 verbosity: minimal

before_test:
- cd build
- powershell -Command .\build.ps1
- cd ..

test_script:
- "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" /logger:Appveyor "C:\projects\sourcecode-smartobjects-services-tests\src\Tests\UTest\bin\Release\SourceCode.SmartObjects.Services.Tests.UTest.dll"