version: 1.0.{build}

image: Visual Studio 2017

assembly_info:
  patch: true
  file: 'src\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

nuget:
  disable_publish_on_pr: true  

configuration:
- Release

platform: Any CPU

# scripts to run before build
before_build:
- nuget restore -verbosity quiet
- appveyor AddMessage "This is a test message"

build:
 project: SourceCode.SmartObjects.Services.Tests.sln
 verbosity: minimal
 publish_nuget: true             # package projects with .nuspec files and push to artifacts

test_script:
- vstest.console /Platform:x64 /InIsolation /logger:Appveyor "src\Tests\UTest\bin\Release\SourceCode.SmartObjects.Services.Tests.UTest.dll"

#uncomment to publish to NuGet
#deploy:
#  provider: NuGet
#  api_key:
#    secure: 9ZjxrStO3j210yUXmH4Q5/H7Bkepb+A1f3kn0snparetNCiXA7sYHvQLRVlAt94m
#  on:
#    branch: master
